version: '3.4'

x-vault: &vault
  build:
    context: .
    dockerfile: vault.dockerfile
  volumes:
   - /sys/fs/cgroup:/sys/fs/cgroup:ro
   - ./config/certs:/etc/certs
   - ./tokens:/tokens/
  ports:
    - 8200
  healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:8200/v1/sys/health"]
  privileged: true

services:
  vault-1:
    <<: *vault
    networks:
      vault_net:
        ipv4_address: 172.22.120.10
        aliases:
          - vault-1.vault.local
    hostname: vault-1
  vault-2:
    <<: *vault
    networks:
      vault_net:
        ipv4_address: 172.22.120.11
        aliases:
          - vault-2.vault.local
    hostname: vault-2
    depends_on:
      - vault-1
  vault-3:
    <<: *vault
    networks:
      vault_net:
        ipv4_address: 172.22.120.12
        aliases:
          - vault-3.vault.local
    hostname: vault-3
    depends_on:
      - vault-2
  haproxy:
    image: haproxy:1.8
    volumes:
      - ./config/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./config/certs:/etc/certs
    networks:
      vault_net:
        ipv4_address: 172.22.120.20
    ports:
      - "8201:8201"
      - "8202:8202"
      - "9000:9000"
    depends_on:
      - vault-1
      - vault-2
      - vault-3


networks:
    vault_net:
        ipam:
            driver: default
            config:
                - subnet: 172.22.120.0/24